In [3]:
import pandas as pd

train_df = pd.read_parquet("top15_train.parquet")
test_df = pd.read_parquet("top15_test.parquet")

combined_df = pd.concat([train_df, test_df], ignore_index=True)
combined_df["data_split"] = ["train"] * len(train_df) + ["test"] * len(test_df)

combined_df.to_parquet("combined_dataset.parquet", index=False)

print("Combined shape:", combined_df.shape)
print("Columns:", list(combined_df.columns))
print(combined_df["data_split"].value_counts().to_string())

Combined shape: (210690, 20)
Columns: ['city_id', 'store_id', 'management_group_id', 'first_category_id', 'second_category_id', 'third_category_id', 'product_id', 'dt', 'sale_amount', 'hours_sale', 'stock_hour6_22_cnt', 'hours_stock_status', 'discount', 'holiday_flag', 'activity_flag', 'precpt', 'avg_temperature', 'avg_humidity', 'avg_wind_level', 'data_split']
data_split
train    175575
test      35115

In [4]:
combined_df.head()

,city_id,store_id,management_group_id,first_category_id,second_category_id,third_category_id,product_id,dt,sale_amount,hours_sale,stock_hour6_22_cnt,hours_stock_status,discount,holiday_flag,activity_flag,precpt,avg_temperature,avg_humidity,avg_wind_level,data_split
0,0,0,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, ...",13,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.6999,15.48,73.54,1.97,train
1,0,1,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.3, 0.0, 0.0, ...",16,"[1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.7005,15.47,73.53,1.97,train
2,0,2,2,29,78,82,4,2024-03-28,1.3,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",9,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, ...",0.882,0,1,1.7000,15.72,73.51,1.51,train
3,0,12,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.2, ...",13,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.7000,15.48,73.54,1.97,train
4,0,18,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, ...",10,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, ...",0.814,0,1,1.7008,16.03,73.48,1.36,train

In [ ]:
combined_df.isnull().sum()

city_id                0
store_id               0
management_group_id    0
first_category_id      0
second_category_id     0
third_category_id      0
product_id             0
dt                     0
sale_amount            0
hours_sale             0
stock_hour6_22_cnt     0
hours_stock_status     0
discount               0
holiday_flag           0
activity_flag          0
precpt                 0
avg_temperature        0
avg_humidity           0
avg_wind_level         0
data_split             0
dtype: int64

In [ ]:
# import pandas as pd

# combined_df = combined_df.copy()
# combined_df["dt"] = pd.to_datetime(combined_df["dt"])
# combined_df = combined_df.sort_values(["product_id", "dt"]).reset_index(drop=True)

# split_frames = []
# for _, group in combined_df.groupby("product_id", sort=False):
#     group = group.sort_values("dt")
#     unique_dates = sorted(group["dt"].dropna().unique())

#     if len(unique_dates) < 15:
#         group["data_split"] = "train"
#     else:
#         cutoff_date = unique_dates[-15]
#         group["data_split"] = group["dt"].ge(cutoff_date).map({True: "test", False: "train"})

#     split_frames.append(group)

# combined_df = pd.concat(split_frames, ignore_index=True)
# train_df = combined_df[combined_df["data_split"] == "train"].copy()
# test_df = combined_df[combined_df["data_split"] == "test"].copy()

# print("Train rows:", len(train_df))
# print("Test rows:", len(test_df))
# print(train_df["data_split"].value_counts().to_string())
# print(test_df["data_split"].value_counts().to_string())

Train rows: 175575
Test rows: 35115
data_split
train    175575
data_split
test    35115

In [ ]:
# train_df.head()

,city_id,store_id,management_group_id,first_category_id,second_category_id,third_category_id,product_id,dt,sale_amount,hours_sale,stock_hour6_22_cnt,hours_stock_status,discount,holiday_flag,activity_flag,precpt,avg_temperature,avg_humidity,avg_wind_level,data_split
0,0,0,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, ...",13,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.6999,15.48,73.54,1.97,train
1,12,248,2,29,78,82,4,2024-03-28,0.4,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, ...",6,"[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.971,0,0,6.1896,18.14,79.36,2.20,train
2,12,249,2,29,78,82,4,2024-03-28,0.8,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0,"[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.971,0,0,4.6286,16.69,78.93,2.55,train
3,12,250,2,29,78,82,4,2024-03-28,0.9,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, ...",6,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.971,0,0,4.6270,17.92,78.78,2.30,train
4,12,251,2,29,78,82,4,2024-03-28,0.6,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",5,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0.971,0,0,4.6280,18.18,78.69,2.27,train

In [ ]:
# import pandas as pd

# # Directly read the rows from test_df for product 4 on the requested day
# if 'test_df' in locals():
#     test_df_copy = test_df.copy()
#     test_df_copy['dt'] = pd.to_datetime(test_df_copy['dt'])
#     day_label = '2024_06_11'
#     sku_4_test = test_df_copy[
#         (test_df_copy['product_id'] == 4) &
#         (test_df_copy['dt'].dt.strftime('%Y_%m_%d') == day_label)&
#         (test_df_copy['store_id'] == 0)
#     ]
#     print(sku_4_test)
# else:
#     print('test_df is not available in this notebook context.')

       city_id  store_id  management_group_id  first_category_id  \
59240        0         0                    2                 29

       second_category_id  third_category_id  product_id         dt  \
59240                  78                 82           4 2024-06-11

       sale_amount                                         hours_sale  \
59240          0.8  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

       stock_hour6_22_cnt                                 hours_stock_status  \
59240                   0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

       discount  holiday_flag  activity_flag  precpt  avg_temperature  \
59240     0.881             0              1  5.6895             25.3

       avg_humidity  avg_wind_level data_split
59240         76.54            1.64       test

In [ ]:
# import numpy as np
# import pandas as pd
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Input, SimpleRNN, Dense
# from tensorflow.keras.optimizers import Adam

# # Use the combined dataset if it is already loaded; otherwise read it from disk
# if 'combined_df' not in locals():
#     combined_df = pd.read_parquet('combined_dataset.parquet')

# # Build a store-SKU hourly series for the example
# combined_df = combined_df.copy()
# combined_df['dt'] = pd.to_datetime(combined_df['dt'])

# # Keep only the columns needed for the example
# example_df = combined_df[['store_id', 'product_id', 'dt', 'hours_stock_status']].copy()

# # Expand the 24-hour stock status list into hourly rows
# example_df['hourly_status'] = example_df['hours_stock_status'].apply(lambda x: list(x) if isinstance(x, (list, np.ndarray)) else [])
# example_df = example_df.explode('hourly_status').reset_index(drop=True)
# example_df['hour'] = example_df.groupby(['store_id', 'product_id', 'dt']).cumcount()
# example_df['stock_status'] = example_df['hourly_status'].astype(int)
# # Encode a stockout as 1 and a non-stockout as 0 for binary classification
# example_df['stockout_label'] = (example_df['stock_status'] == 0).astype(int)

# # Keep one sequence per store-SKU pair
# store_sku_df = example_df[['store_id', 'product_id', 'dt', 'hour', 'stock_status', 'stockout_label']].copy()
# store_sku_df['timestamp'] = pd.to_datetime(store_sku_df['dt']) + pd.to_timedelta(store_sku_df['hour'], unit='h')
# store_sku_df = store_sku_df.sort_values(['store_id', 'product_id', 'timestamp']).reset_index(drop=True)

# # Pick one store-SKU pair for the example
# store_id = 0
# sku_id = 4
# pair_df = store_sku_df[(store_sku_df['store_id'] == store_id) & (store_sku_df['product_id'] == sku_id)].copy()
# pair_df = pair_df.sort_values('timestamp').reset_index(drop=True)
# series = pair_df['stockout_label'].to_numpy(dtype='float32')

# # Use the first 75 days for training and the next 15 days for testing
# train_days = 75
# train_len = train_days * 24
# forecast_horizon = 15 * 24
# lookback = 24


# def make_sequences(values, lookback):
#     X, y = [], []
#     for i in range(lookback, len(values)):
#         X.append(values[i-lookback:i])
#         y.append(values[i])
#     return np.array(X, dtype='float32').reshape(-1, lookback, 1), np.array(y, dtype='float32').reshape(-1, 1)

# X_train, y_train = make_sequences(series[:train_len], lookback)

# model = Sequential([
#     Input(shape=(lookback, 1)),
#     SimpleRNN(16, activation='tanh'),
#     Dense(1, activation='sigmoid')
# ])
# model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])
# model.fit(X_train, y_train, epochs=10, batch_size=32, verbose=0)

# # Recursive one-step-ahead forecast for the next 15 days of hourly data
# history = series[:train_len][-lookback:].copy()
# forecast_prob = []
# for _ in range(forecast_horizon):
#     x = history[-lookback:].reshape(1, lookback, 1)
#     prob = model.predict(x, verbose=0)[0, 0]
#     forecast_prob.append(float(prob))
#     history = np.append(history, prob)

# actual = series[train_len:train_len + forecast_horizon]
# forecast_label = (np.array(forecast_prob) >= 0.5).astype(int)
# accuracy = np.mean(forecast_label == actual)

# print('Store:', store_id)
# print('SKU:', sku_id)
# print('Training hours:', train_len)
# print('Forecast horizon hours:', forecast_horizon)
# print('Forecast probabilities (first 10 hours):', np.round(forecast_prob[:10], 4))
# print('Predicted labels (first 10 hours):', forecast_label[:10])
# print('Original stock status (first 10 hours):', pair_df['stock_status'].iloc[train_len:train_len+10].astype(int).tolist())
# print('Encoded stockout labels (first 10 hours):', actual[:10].astype(int).tolist())
# print('Accuracy:', round(float(accuracy), 4))

Store: 0
SKU: 4
Training hours: 1800
Forecast horizon hours: 360
Forecast probabilities (first 10 hours): [0.9665 0.9642 0.9624 0.9618 0.9618 0.9614 0.9613 0.9616 0.9617 0.9619]
Predicted labels (first 10 hours): [1 1 1 1 1 1 1 1 1 1]
Original stock status (first 10 hours): [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Encoded stockout labels (first 10 hours): [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Accuracy: 0.9417

In [3]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, SimpleRNN, Dense
from tensorflow.keras.optimizers import Adam

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1783078173.738591   14908 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1783078174.468724   14908 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1783078177.058495   14908 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [4]:
if 'combined_df' not in locals():
    combined_df = pd.read_parquet("combined_dataset.parquet")

combined_df = combined_df.copy()

combined_df["dt"] = pd.to_datetime(combined_df["dt"])

In [5]:
combined_df.head()

,city_id,store_id,management_group_id,first_category_id,second_category_id,third_category_id,product_id,dt,sale_amount,hours_sale,stock_hour6_22_cnt,hours_stock_status,discount,holiday_flag,activity_flag,precpt,avg_temperature,avg_humidity,avg_wind_level,data_split
0,0,0,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, ...",13,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.6999,15.48,73.54,1.97,train
1,0,1,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.3, 0.0, 0.0, ...",16,"[1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.7005,15.47,73.53,1.97,train
2,0,2,2,29,78,82,4,2024-03-28,1.3,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",9,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, ...",0.882,0,1,1.7000,15.72,73.51,1.51,train
3,0,12,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.2, ...",13,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.7000,15.48,73.54,1.97,train
4,0,18,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, ...",10,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, ...",0.814,0,1,1.7008,16.03,73.48,1.36,train

In [6]:
combined_df["daily_stockout"] = combined_df["hours_stock_status"].apply(
    lambda x: int(np.any(np.array(x) == 1))
)
combined_df[["hours_stock_status","daily_stockout"]].head()

                                  hours_stock_status  daily_stockout
0  [1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...               1
1  [1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...               1
2  [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, ...               1
3  [1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...               1
4  [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, ...               1

In [7]:
combined_df["avg_hourly_sales"] = combined_df["hours_sale"].apply(np.mean)

combined_df["max_hourly_sales"] = combined_df["hours_sale"].apply(np.max)

combined_df["std_hourly_sales"] = combined_df["hours_sale"].apply(np.std)

In [8]:
feature_cols = [

    # Product hierarchy
    "city_id",
    "management_group_id",
    "first_category_id",
    "second_category_id",
    "third_category_id",

    # Sales
    "sale_amount",
    "avg_hourly_sales",
    "max_hourly_sales",
    "std_hourly_sales",

    # Inventory
    "stock_hour6_22_cnt",

    # Pricing
    "discount",

    # Calendar
    "holiday_flag",
    "activity_flag",

    # Weather
    "precpt",
    "avg_temperature",
    "avg_humidity",
    "avg_wind_level"
]


target = "daily_stockout"

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

combined_df[feature_cols] = scaler.fit_transform(
    combined_df[feature_cols]
)

In [10]:
LOOKBACK = 7
TRAIN_DAYS = 75

In [11]:
X_train = []
y_train = []

X_test = []
y_test = []

for (_, _), group in combined_df.groupby(["store_id", "product_id"]):

    group = group.sort_values("dt").reset_index(drop=True)

    if len(group) < 90:
        continue

    features = group[feature_cols].values
    labels = group[target].values

    # ---------- Training ----------
    for i in range(LOOKBACK, TRAIN_DAYS):

        X_train.append(features[i-LOOKBACK:i])
        y_train.append(labels[i])

    # ---------- Testing ----------
    for i in range(TRAIN_DAYS, len(group)):

        X_test.append(features[i-LOOKBACK:i])
        y_test.append(labels[i])

In [ ]:
X_train = np.array(X_train, dtype=np.float32)
y_train = np.array(y_train, dtype=np.float32)

X_test = np.array(X_test, dtype=np.float32)
y_test = np.array(y_test, dtype=np.float32)

In [13]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(159188, 7, 17)
(159188,)
(35115, 7, 17)
(35115,)

In [14]:
model = Sequential([
    Input(shape=(LOOKBACK, X_train.shape[2])),
    SimpleRNN(32, activation="tanh"),
    Dense(1, activation="sigmoid")
])

In [15]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [16]:
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=20,
    batch_size=64,
    verbose=1
)

Epoch 1/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.7788 - loss: 0.4452 - val_accuracy: 0.7310 - val_loss: 0.5033
Epoch 2/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.7938 - loss: 0.4202 - val_accuracy: 0.7519 - val_loss: 0.4831
Epoch 3/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.7990 - loss: 0.4131 - val_accuracy: 0.7669 - val_loss: 0.4786
Epoch 4/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.8020 - loss: 0.4087 - val_accuracy: 0.7677 - val_loss: 0.4807
Epoch 5/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.8051 - loss: 0.4046 - val_accuracy: 0.7648 - val_loss: 0.4775
Epoch 6/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.8067 - loss: 0.4018 - val_accuracy: 0.7693 - val_loss: 0.4773
Epoch 7/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8081 - loss: 0.3993 - val_accuracy: 0.7581 - val_loss: 0.4890
Epoch 8/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.8103 - loss: 0.3973 - val_accuracy: 0.7363 - val_loss: 0.5000
Epoch 9/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.8119 - loss: 0.3953 - val_accuracy: 0.7645 - val_loss: 0.4870
Epoch 10/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8121 - loss: 0.3940 - val_accuracy: 0.7503 - val_loss: 0.4929
Epoch 11/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.8134 - loss: 0.3929 - val_accuracy: 0.7598 - val_loss: 0.4928
Epoch 12/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.8133 - loss: 0.3919 - val_accuracy: 0.7540 - val_loss: 0.4924
Epoch 13/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.8144 - loss: 0.3910 - val_accuracy: 0.7644 - val_loss: 0.4851
Epoch 14/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.8155 - loss: 0.3902 - val_accuracy: 0.7661 - val_loss: 0.4854
Epoch 15/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.8157 - loss: 0.3893 - val_accuracy: 0.7594 - val_loss: 0.4957
Epoch 16/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.8162 - loss: 0.3886 - val_accuracy: 0.7607 - val_loss: 0.4928
Epoch 17/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.8173 - loss: 0.3879 - val_accuracy: 0.7630 - val_loss: 0.4992
Epoch 18/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.8171 - loss: 0.3873 - val_accuracy: 0.7540 - val_loss: 0.4990
Epoch 19/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.8183 - loss: 0.3869 - val_accuracy: 0.7479 - val_loss: 0.5075
Epoch 20/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8179 - loss: 0.3862 - val_accuracy: 0.7407 - val_loss: 0.4994

In [17]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

1098/1098 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7407 - loss: 0.4994
Test Loss: 0.49940240383148193
Test Accuracy: 0.7407375574111938

In [18]:
print(pd.Series(y_train).value_counts())
print(pd.Series(y_test).value_counts())

1.0    109290
0.0     49898
Name: count, dtype: int64
1.0    21221
0.0    13894
Name: count, dtype: int64

In [19]:
store = 0
sku = 4
prediction_day = pd.Timestamp("2024-06-11")

In [20]:
group = combined_df[
    (combined_df["store_id"] == store) &
    (combined_df["product_id"] == sku)
].sort_values("dt")

history = group[group["dt"] < prediction_day].tail(LOOKBACK)

if len(history) != LOOKBACK:
    print(len(history))

In [21]:
X = history[feature_cols].values.astype(np.float32)
X = X.reshape(1, LOOKBACK, len(feature_cols))

In [22]:
prob = model.predict(X, verbose=0)[0, 0]

prediction = int(prob >= 0.5)

print("Probability of stockout:", prob)
print("Prediction:", prediction)

Probability of stockout: 0.4291289
Prediction: 0