In [4]:
import pandas as pd

train_df = pd.read_parquet("top15_train.parquet")
test_df = pd.read_parquet("top15_test.parquet")

combined_df = pd.concat([train_df, test_df], ignore_index=True)
combined_df["data_split"] = ["train"] * len(train_df) + ["test"] * len(test_df)

combined_df.to_parquet("combined_dataset.parquet", index=False)

print("Combined shape:", combined_df.shape)
print("Columns:", list(combined_df.columns))
print(combined_df["data_split"].value_counts().to_string())

Combined shape: (210690, 20)
Columns: ['city_id', 'store_id', 'management_group_id', 'first_category_id', 'second_category_id', 'third_category_id', 'product_id', 'dt', 'sale_amount', 'hours_sale', 'stock_hour6_22_cnt', 'hours_stock_status', 'discount', 'holiday_flag', 'activity_flag', 'precpt', 'avg_temperature', 'avg_humidity', 'avg_wind_level', 'data_split']
data_split
train    175575
test      35115

In [5]:
combined_df.head()

,city_id,store_id,management_group_id,first_category_id,second_category_id,third_category_id,product_id,dt,sale_amount,hours_sale,stock_hour6_22_cnt,hours_stock_status,discount,holiday_flag,activity_flag,precpt,avg_temperature,avg_humidity,avg_wind_level,data_split
0,0,0,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, ...",13,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.6999,15.48,73.54,1.97,train
1,0,1,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.3, 0.0, 0.0, ...",16,"[1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.7005,15.47,73.53,1.97,train
2,0,2,2,29,78,82,4,2024-03-28,1.3,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",9,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, ...",0.882,0,1,1.7000,15.72,73.51,1.51,train
3,0,12,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.2, ...",13,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.7000,15.48,73.54,1.97,train
4,0,18,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, ...",10,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, ...",0.814,0,1,1.7008,16.03,73.48,1.36,train

In [6]:
combined_df.isnull().sum()

city_id                0
store_id               0
management_group_id    0
first_category_id      0
second_category_id     0
third_category_id      0
product_id             0
dt                     0
sale_amount            0
hours_sale             0
stock_hour6_22_cnt     0
hours_stock_status     0
discount               0
holiday_flag           0
activity_flag          0
precpt                 0
avg_temperature        0
avg_humidity           0
avg_wind_level         0
data_split             0
dtype: int64

In [7]:
# import pandas as pd

# combined_df = combined_df.copy()
# combined_df["dt"] = pd.to_datetime(combined_df["dt"])
# combined_df = combined_df.sort_values(["product_id", "dt"]).reset_index(drop=True)

# split_frames = []
# for _, group in combined_df.groupby("product_id", sort=False):
#     group = group.sort_values("dt")
#     unique_dates = sorted(group["dt"].dropna().unique())

#     if len(unique_dates) < 15:
#         group["data_split"] = "train"
#     else:
#         cutoff_date = unique_dates[-15]
#         group["data_split"] = group["dt"].ge(cutoff_date).map({True: "test", False: "train"})

#     split_frames.append(group)

# combined_df = pd.concat(split_frames, ignore_index=True)
# train_df = combined_df[combined_df["data_split"] == "train"].copy()
# test_df = combined_df[combined_df["data_split"] == "test"].copy()

# print("Train rows:", len(train_df))
# print("Test rows:", len(test_df))
# print(train_df["data_split"].value_counts().to_string())
# print(test_df["data_split"].value_counts().to_string())

In [8]:
# train_df.head()

In [9]:
# import pandas as pd

# # Directly read the rows from test_df for product 4 on the requested day
# if 'test_df' in locals():
#     test_df_copy = test_df.copy()
#     test_df_copy['dt'] = pd.to_datetime(test_df_copy['dt'])
#     day_label = '2024_06_11'
#     sku_4_test = test_df_copy[
#         (test_df_copy['product_id'] == 4) &
#         (test_df_copy['dt'].dt.strftime('%Y_%m_%d') == day_label)&
#         (test_df_copy['store_id'] == 0)
#     ]
#     print(sku_4_test)
# else:
#     print('test_df is not available in this notebook context.')

In [10]:
# import numpy as np
# import pandas as pd
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Input, SimpleRNN, Dense
# from tensorflow.keras.optimizers import Adam

# # Use the combined dataset if it is already loaded; otherwise read it from disk
# if 'combined_df' not in locals():
#     combined_df = pd.read_parquet('combined_dataset.parquet')

# # Build a store-SKU hourly series for the example
# combined_df = combined_df.copy()
# combined_df['dt'] = pd.to_datetime(combined_df['dt'])

# # Keep only the columns needed for the example
# example_df = combined_df[['store_id', 'product_id', 'dt', 'hours_stock_status']].copy()

# # Expand the 24-hour stock status list into hourly rows
# example_df['hourly_status'] = example_df['hours_stock_status'].apply(lambda x: list(x) if isinstance(x, (list, np.ndarray)) else [])
# example_df = example_df.explode('hourly_status').reset_index(drop=True)
# example_df['hour'] = example_df.groupby(['store_id', 'product_id', 'dt']).cumcount()
# example_df['stock_status'] = example_df['hourly_status'].astype(int)
# # Encode a stockout as 1 and a non-stockout as 0 for binary classification
# example_df['stockout_label'] = (example_df['stock_status'] == 0).astype(int)

# # Keep one sequence per store-SKU pair
# store_sku_df = example_df[['store_id', 'product_id', 'dt', 'hour', 'stock_status', 'stockout_label']].copy()
# store_sku_df['timestamp'] = pd.to_datetime(store_sku_df['dt']) + pd.to_timedelta(store_sku_df['hour'], unit='h')
# store_sku_df = store_sku_df.sort_values(['store_id', 'product_id', 'timestamp']).reset_index(drop=True)

# # Pick one store-SKU pair for the example
# store_id = 0
# sku_id = 4
# pair_df = store_sku_df[(store_sku_df['store_id'] == store_id) & (store_sku_df['product_id'] == sku_id)].copy()
# pair_df = pair_df.sort_values('timestamp').reset_index(drop=True)
# series = pair_df['stockout_label'].to_numpy(dtype='float32')

# # Use the first 75 days for training and the next 15 days for testing
# train_days = 75
# train_len = train_days * 24
# forecast_horizon = 15 * 24
# lookback = 24


# def make_sequences(values, lookback):
#     X, y = [], []
#     for i in range(lookback, len(values)):
#         X.append(values[i-lookback:i])
#         y.append(values[i])
#     return np.array(X, dtype='float32').reshape(-1, lookback, 1), np.array(y, dtype='float32').reshape(-1, 1)

# X_train, y_train = make_sequences(series[:train_len], lookback)

# model = Sequential([
#     Input(shape=(lookback, 1)),
#     SimpleRNN(16, activation='tanh'),
#     Dense(1, activation='sigmoid')
# ])
# model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])
# model.fit(X_train, y_train, epochs=10, batch_size=32, verbose=0)

# # Recursive one-step-ahead forecast for the next 15 days of hourly data
# history = series[:train_len][-lookback:].copy()
# forecast_prob = []
# for _ in range(forecast_horizon):
#     x = history[-lookback:].reshape(1, lookback, 1)
#     prob = model.predict(x, verbose=0)[0, 0]
#     forecast_prob.append(float(prob))
#     history = np.append(history, prob)

# actual = series[train_len:train_len + forecast_horizon]
# forecast_label = (np.array(forecast_prob) >= 0.5).astype(int)
# accuracy = np.mean(forecast_label == actual)

# print('Store:', store_id)
# print('SKU:', sku_id)
# print('Training hours:', train_len)
# print('Forecast horizon hours:', forecast_horizon)
# print('Forecast probabilities (first 10 hours):', np.round(forecast_prob[:10], 4))
# print('Predicted labels (first 10 hours):', forecast_label[:10])
# print('Original stock status (first 10 hours):', pair_df['stock_status'].iloc[train_len:train_len+10].astype(int).tolist())
# print('Encoded stockout labels (first 10 hours):', actual[:10].astype(int).tolist())
# print('Accuracy:', round(float(accuracy), 4))

In [11]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Dropout
from tensorflow.keras.optimizers import Adam, RMSprop

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1783942106.543277   21093 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1783942108.583714   21093 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1783942111.833325   21093 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [12]:
if 'combined_df' not in locals():
    combined_df = pd.read_parquet("combined_dataset.parquet")

combined_df = combined_df.copy()

combined_df["dt"] = pd.to_datetime(combined_df["dt"])

In [13]:
combined_df.head()

,city_id,store_id,management_group_id,first_category_id,second_category_id,third_category_id,product_id,dt,sale_amount,hours_sale,stock_hour6_22_cnt,hours_stock_status,discount,holiday_flag,activity_flag,precpt,avg_temperature,avg_humidity,avg_wind_level,data_split
0,0,0,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, ...",13,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.6999,15.48,73.54,1.97,train
1,0,1,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.3, 0.0, 0.0, ...",16,"[1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.7005,15.47,73.53,1.97,train
2,0,2,2,29,78,82,4,2024-03-28,1.3,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",9,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, ...",0.882,0,1,1.7000,15.72,73.51,1.51,train
3,0,12,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.0, 0.0, 0.2, ...",13,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...",0.882,0,1,1.7000,15.48,73.54,1.97,train
4,0,18,2,29,78,82,4,2024-03-28,0.5,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, ...",10,"[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, ...",0.814,0,1,1.7008,16.03,73.48,1.36,train

In [14]:
combined_df["daily_stockout"] = combined_df["hours_stock_status"].apply(
    lambda x: int(np.any(np.array(x) == 1))
)
combined_df[["hours_stock_status","daily_stockout"]].head()

                                  hours_stock_status  daily_stockout
0  [1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...               1
1  [1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...               1
2  [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, ...               1
3  [1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ...               1
4  [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, ...               1

In [15]:
combined_df["avg_hourly_sales"] = combined_df["hours_sale"].apply(np.mean)

combined_df["max_hourly_sales"] = combined_df["hours_sale"].apply(np.max)

combined_df["std_hourly_sales"] = combined_df["hours_sale"].apply(np.std)

In [16]:
feature_cols = [

    # Product hierarchy
    "city_id",
    "management_group_id",
    "first_category_id",
    "second_category_id",
    "third_category_id",

    # Sales
    "sale_amount",
    "avg_hourly_sales",
    "max_hourly_sales",
    "std_hourly_sales",

    # Inventory
    "stock_hour6_22_cnt",

    # Pricing
    "discount",

    # Calendar
    "holiday_flag",
    "activity_flag",

    # Weather
    "precpt",
    "avg_temperature",
    "avg_humidity",
    "avg_wind_level"
]


target = "daily_stockout"

In [17]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

combined_df[feature_cols] = scaler.fit_transform(
    combined_df[feature_cols]
)

In [18]:
LOOKBACK = 7
TRAIN_DAYS = 75

In [19]:
X_train = []
y_train = []

X_test = []
y_test = []

for (_, _), group in combined_df.groupby(["store_id", "product_id"]):

    group = group.sort_values("dt").reset_index(drop=True)

    if len(group) < 90:
        continue

    features = group[feature_cols].values
    labels = group[target].values

    # ---------- Training ----------
    for i in range(LOOKBACK, TRAIN_DAYS):

        X_train.append(features[i-LOOKBACK:i])
        y_train.append(labels[i])

    # ---------- Testing ----------
    for i in range(TRAIN_DAYS, len(group)):

        X_test.append(features[i-LOOKBACK:i])
        y_test.append(labels[i])

In [20]:
X_train = np.array(X_train, dtype=np.float32)
y_train = np.array(y_train, dtype=np.float32)

X_test = np.array(X_test, dtype=np.float32)
y_test = np.array(y_test, dtype=np.float32)

In [21]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(159188, 7, 17)
(159188,)
(35115, 7, 17)
(35115,)

In [22]:
print("Training Varation 1: Baseline")
model = Sequential([
    Input(shape=(LOOKBACK, X_train.shape[2])),
    SimpleRNN(32, activation="tanh"),
    Dense(1, activation="sigmoid")
])
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=20,
    batch_size=64,
    verbose=1
)

Training Varation 1: Baseline
Epoch 1/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.7775 - loss: 0.4455 - val_accuracy: 0.7606 - val_loss: 0.4833
Epoch 2/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.7971 - loss: 0.4188 - val_accuracy: 0.7613 - val_loss: 0.4886
Epoch 3/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.8024 - loss: 0.4101 - val_accuracy: 0.7602 - val_loss: 0.4863
Epoch 4/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.8056 - loss: 0.4053 - val_accuracy: 0.7678 - val_loss: 0.4704
Epoch 5/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.8071 - loss: 0.4020 - val_accuracy: 0.7641 - val_loss: 0.4793
Epoch 6/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8094 - loss: 0.3990 - val_accuracy: 0.7684 - val_loss: 0.4800
Epoch 7/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.8112 - loss: 0.3971 - val_accuracy: 0.7686 - val_loss: 0.4755
Epoch 8/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.8117 - loss: 0.3954 - val_accuracy: 0.7703 - val_loss: 0.4741
Epoch 9/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.8128 - loss: 0.3939 - val_accuracy: 0.7659 - val_loss: 0.4758
Epoch 10/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.8149 - loss: 0.3922 - val_accuracy: 0.7686 - val_loss: 0.4889
Epoch 11/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.8156 - loss: 0.3909 - val_accuracy: 0.7679 - val_loss: 0.4780
Epoch 12/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8166 - loss: 0.3899 - val_accuracy: 0.7687 - val_loss: 0.4830
Epoch 13/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.8168 - loss: 0.3885 - val_accuracy: 0.7667 - val_loss: 0.4775
Epoch 14/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.8174 - loss: 0.3882 - val_accuracy: 0.7587 - val_loss: 0.4872
Epoch 15/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.8180 - loss: 0.3873 - val_accuracy: 0.7595 - val_loss: 0.4937
Epoch 16/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8186 - loss: 0.3867 - val_accuracy: 0.7600 - val_loss: 0.4914
Epoch 17/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.8187 - loss: 0.3862 - val_accuracy: 0.7620 - val_loss: 0.4950
Epoch 18/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.8195 - loss: 0.3856 - val_accuracy: 0.7652 - val_loss: 0.4911
Epoch 19/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8194 - loss: 0.3850 - val_accuracy: 0.7578 - val_loss: 0.5033
Epoch 20/20
2488/2488 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.8204 - loss: 0.3840 - val_accuracy: 0.7588 - val_loss: 0.4895

In [37]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

1098/1098 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7588 - loss: 0.4895
Test Loss: 0.48954516649246216
Test Accuracy: 0.7587640881538391

In [24]:
#Increasing the number of units from 32 to 64 to see if the model can learn more complex         
#patterns.                                                                                       
                                                                                                  
print("Training Variation 2: Higher Capacity (64 Units)")                                     
model_2 = Sequential([                                                                        
        Input(shape=(LOOKBACK, X_train.shape[2])),                                                
        SimpleRNN(64, activation="tanh"),                                                         
        Dense(1, activation="sigmoid")                                                            
    ])                                                                                            
                                                                                                  
model_2.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])           
                                                                                                  
history_2 = model_2.fit(                                                                      
        X_train, y_train,                                                                         
        epochs=20,                                                                                
        batch_size=32,                                                                            
        validation_data=(X_test, y_test),                                                         
        verbose=1                                                                                 
    )

Training Variation 2: Higher Capacity (64 Units)
Epoch 1/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 23s 4ms/step - accuracy: 0.7842 - loss: 0.4352 - val_accuracy: 0.7656 - val_loss: 0.4814
Epoch 2/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 19s 4ms/step - accuracy: 0.8010 - loss: 0.4122 - val_accuracy: 0.7665 - val_loss: 0.4760
Epoch 3/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 21s 4ms/step - accuracy: 0.8069 - loss: 0.4030 - val_accuracy: 0.7686 - val_loss: 0.4756
Epoch 4/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.8109 - loss: 0.3969 - val_accuracy: 0.7675 - val_loss: 0.4774
Epoch 5/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8146 - loss: 0.3918 - val_accuracy: 0.7584 - val_loss: 0.4828
Epoch 6/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 21s 4ms/step - accuracy: 0.8173 - loss: 0.3887 - val_accuracy: 0.7564 - val_loss: 0.4917
Epoch 7/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.8197 - loss: 0.3859 - val_accuracy: 0.7610 - val_loss: 0.4884
Epoch 8/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.8209 - loss: 0.3827 - val_accuracy: 0.7513 - val_loss: 0.4973
Epoch 9/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.8228 - loss: 0.3808 - val_accuracy: 0.7585 - val_loss: 0.4982
Epoch 10/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8239 - loss: 0.3790 - val_accuracy: 0.7610 - val_loss: 0.5105
Epoch 11/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.8251 - loss: 0.3767 - val_accuracy: 0.7606 - val_loss: 0.5097
Epoch 12/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 20s 4ms/step - accuracy: 0.8265 - loss: 0.3755 - val_accuracy: 0.7498 - val_loss: 0.5060
Epoch 13/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.8269 - loss: 0.3742 - val_accuracy: 0.7582 - val_loss: 0.5136
Epoch 14/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 21s 4ms/step - accuracy: 0.8268 - loss: 0.3733 - val_accuracy: 0.7505 - val_loss: 0.5097
Epoch 15/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 21s 4ms/step - accuracy: 0.8282 - loss: 0.3719 - val_accuracy: 0.7580 - val_loss: 0.5071
Epoch 16/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.8289 - loss: 0.3708 - val_accuracy: 0.7524 - val_loss: 0.5131
Epoch 17/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - accuracy: 0.8296 - loss: 0.3703 - val_accuracy: 0.7592 - val_loss: 0.5057
Epoch 18/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.8296 - loss: 0.3693 - val_accuracy: 0.7394 - val_loss: 0.5274
Epoch 19/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 21s 4ms/step - accuracy: 0.8306 - loss: 0.3686 - val_accuracy: 0.7607 - val_loss: 0.5108
Epoch 20/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.8307 - loss: 0.3679 - val_accuracy: 0.7528 - val_loss: 0.5287

In [25]:
#Stacking two RNN layers together. The first layer must return sequences so the second layer can 
#read them.                                                                                      
                                                                                                  
print("Training Variation 3: Stacked RNN")                                                    
model_3 = Sequential([                                                                        
        Input(shape=(LOOKBACK, X_train.shape[2])),                                                
        SimpleRNN(32, activation="tanh", return_sequences=True),                                  
        SimpleRNN(16, activation="tanh"),                                                         
        Dense(1, activation="sigmoid")                                                            
    ])                                                                                            
                                                                                                  
model_3.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])           
                                                                                                  
history_3 = model_3.fit(                                                                      
        X_train, y_train,                                                                         
        epochs=20,                                                                                
        batch_size=32,                                                                            
        validation_data=(X_test, y_test),                                                         
        verbose=1                                                                                 
    )

Training Variation 3: Stacked RNN
Epoch 1/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 29s 5ms/step - accuracy: 0.7826 - loss: 0.4340 - val_accuracy: 0.7521 - val_loss: 0.4827
Epoch 2/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 26s 5ms/step - accuracy: 0.7981 - loss: 0.4117 - val_accuracy: 0.7581 - val_loss: 0.4778
Epoch 3/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - accuracy: 0.8036 - loss: 0.4053 - val_accuracy: 0.7563 - val_loss: 0.4972
Epoch 4/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 27s 5ms/step - accuracy: 0.8064 - loss: 0.4011 - val_accuracy: 0.7632 - val_loss: 0.4784
Epoch 5/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 27s 5ms/step - accuracy: 0.8093 - loss: 0.3975 - val_accuracy: 0.7547 - val_loss: 0.4850
Epoch 6/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 27s 5ms/step - accuracy: 0.8128 - loss: 0.3949 - val_accuracy: 0.7540 - val_loss: 0.4901
Epoch 7/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - accuracy: 0.8129 - loss: 0.3927 - val_accuracy: 0.7360 - val_loss: 0.5008
Epoch 8/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 27s 5ms/step - accuracy: 0.8148 - loss: 0.3910 - val_accuracy: 0.7530 - val_loss: 0.4901
Epoch 9/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 28s 6ms/step - accuracy: 0.8164 - loss: 0.3890 - val_accuracy: 0.7552 - val_loss: 0.4875
Epoch 10/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 27s 5ms/step - accuracy: 0.8170 - loss: 0.3876 - val_accuracy: 0.7591 - val_loss: 0.4845
Epoch 11/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - accuracy: 0.8183 - loss: 0.3864 - val_accuracy: 0.7568 - val_loss: 0.4988
Epoch 12/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 27s 5ms/step - accuracy: 0.8191 - loss: 0.3852 - val_accuracy: 0.7515 - val_loss: 0.4888
Epoch 13/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 27s 5ms/step - accuracy: 0.8195 - loss: 0.3844 - val_accuracy: 0.7663 - val_loss: 0.4856
Epoch 14/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 27s 5ms/step - accuracy: 0.8199 - loss: 0.3832 - val_accuracy: 0.7420 - val_loss: 0.4980
Epoch 15/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - accuracy: 0.8214 - loss: 0.3829 - val_accuracy: 0.7527 - val_loss: 0.4968
Epoch 16/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 28s 6ms/step - accuracy: 0.8208 - loss: 0.3823 - val_accuracy: 0.7372 - val_loss: 0.5064
Epoch 17/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 27s 6ms/step - accuracy: 0.8216 - loss: 0.3813 - val_accuracy: 0.7327 - val_loss: 0.5088
Epoch 18/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 28s 6ms/step - accuracy: 0.8223 - loss: 0.3804 - val_accuracy: 0.7600 - val_loss: 0.4900
Epoch 19/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - accuracy: 0.8219 - loss: 0.3799 - val_accuracy: 0.7501 - val_loss: 0.4941
Epoch 20/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 28s 6ms/step - accuracy: 0.8225 - loss: 0.3796 - val_accuracy: 0.7564 - val_loss: 0.4937

In [26]:
  ### Variation 4: RNN with Dropout and Extra Dense Layer                                         
                                                                                                  
#Adding dropout to prevent overfitting, and an intermediate Dense layer to help process the RNN  
#output before the final classification. We also switch to  RMSprop .                            
                                                                                                  
print("Training Variation 4: Dropout, Extra Dense, and RMSprop")                              
model_4 = Sequential([                                                                        
        Input(shape=(LOOKBACK, X_train.shape[2])),                                                
        SimpleRNN(32, activation="tanh", dropout=0.2, recurrent_dropout=0.2),                     
        Dense(16, activation="relu"),                                                             
        Dense(1, activation="sigmoid")                                                            
    ])                                                                                            
                                                                                                  
model_4.compile(                                                                              
        optimizer=RMSprop(learning_rate=0.001),                                                   
        loss="binary_crossentropy",                                                               
        metrics=["accuracy"]                                                                      
    )                                                                                             
                                                                                                  
history_4 = model_4.fit(                                                                      
        X_train, y_train,                                                                         
        epochs=20,                                                                                
        batch_size=32,                                                                            
        validation_data=(X_test, y_test),                                                         
        verbose=1                                                                                 
    )

Training Variation 4: Dropout, Extra Dense, and RMSprop
Epoch 1/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - accuracy: 0.7501 - loss: 0.4926 - val_accuracy: 0.7420 - val_loss: 0.4981
Epoch 2/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 18s 4ms/step - accuracy: 0.7606 - loss: 0.4739 - val_accuracy: 0.7567 - val_loss: 0.4806
Epoch 3/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - accuracy: 0.7639 - loss: 0.4665 - val_accuracy: 0.7561 - val_loss: 0.4793
Epoch 4/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.7630 - loss: 0.4634 - val_accuracy: 0.7323 - val_loss: 0.4886
Epoch 5/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 18s 4ms/step - accuracy: 0.7665 - loss: 0.4607 - val_accuracy: 0.7425 - val_loss: 0.4838
Epoch 6/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - accuracy: 0.7671 - loss: 0.4586 - val_accuracy: 0.7402 - val_loss: 0.4838
Epoch 7/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 19s 4ms/step - accuracy: 0.7667 - loss: 0.4584 - val_accuracy: 0.7215 - val_loss: 0.5063
Epoch 8/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.7684 - loss: 0.4567 - val_accuracy: 0.7422 - val_loss: 0.4798
Epoch 9/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 19s 4ms/step - accuracy: 0.7679 - loss: 0.4555 - val_accuracy: 0.6964 - val_loss: 0.5020
Epoch 10/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.7679 - loss: 0.4561 - val_accuracy: 0.6853 - val_loss: 0.5094
Epoch 11/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.7692 - loss: 0.4550 - val_accuracy: 0.7063 - val_loss: 0.4977
Epoch 12/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 19s 4ms/step - accuracy: 0.7695 - loss: 0.4537 - val_accuracy: 0.6818 - val_loss: 0.5224
Epoch 13/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 19s 4ms/step - accuracy: 0.7699 - loss: 0.4533 - val_accuracy: 0.7121 - val_loss: 0.4996
Epoch 14/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 25s 5ms/step - accuracy: 0.7689 - loss: 0.4548 - val_accuracy: 0.7352 - val_loss: 0.4876
Epoch 15/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - accuracy: 0.7694 - loss: 0.4534 - val_accuracy: 0.6685 - val_loss: 0.5258
Epoch 16/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 18s 4ms/step - accuracy: 0.7722 - loss: 0.4524 - val_accuracy: 0.7066 - val_loss: 0.5033
Epoch 17/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.7704 - loss: 0.4532 - val_accuracy: 0.7080 - val_loss: 0.5051
Epoch 18/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 19s 4ms/step - accuracy: 0.7717 - loss: 0.4527 - val_accuracy: 0.7190 - val_loss: 0.4978
Epoch 19/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.7719 - loss: 0.4517 - val_accuracy: 0.7039 - val_loss: 0.5163
Epoch 20/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 19s 4ms/step - accuracy: 0.7725 - loss: 0.4519 - val_accuracy: 0.7090 - val_loss: 0.5076

In [27]:
#Using  relu  in the RNN layer instead of  tanh . Since  relu  can cause exploding gradients in  
#RNNs, we MUST use gradient clipping ( clipnorm=1.0 ) in the optimizer.

print("Training Variation 5: ReLU with Gradient Clipping")
model_5 = Sequential([
        Input(shape=(LOOKBACK, X_train.shape[2])),
        SimpleRNN(32, activation="relu"),
        Dense(1, activation="sigmoid")
    ])

    # clipnorm is critical here to prevent the loss from turning to NaN
optimizer_5 = Adam(learning_rate=0.001, clipnorm=1.0)

model_5.compile(
        optimizer=optimizer_5,
        loss="binary_crossentropy",
        metrics=["accuracy"]
    )

history_5 = model_5.fit(
        X_train, y_train,
        epochs=20,
        batch_size=32,
        validation_data=(X_test, y_test),
        verbose=1
    )

Training Variation 5: ReLU with Gradient Clipping
Epoch 1/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 24s 4ms/step - accuracy: 0.7770 - loss: 0.4443 - val_accuracy: 0.7661 - val_loss: 0.4860
Epoch 2/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.7951 - loss: 0.4166 - val_accuracy: 0.7716 - val_loss: 0.4694
Epoch 3/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 18s 4ms/step - accuracy: 0.8002 - loss: 0.4097 - val_accuracy: 0.7618 - val_loss: 0.4789
Epoch 4/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - accuracy: 0.8043 - loss: 0.4055 - val_accuracy: 0.7559 - val_loss: 0.4790
Epoch 5/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 20s 4ms/step - accuracy: 0.8063 - loss: 0.4021 - val_accuracy: 0.7684 - val_loss: 0.4730
Epoch 6/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 21s 4ms/step - accuracy: 0.8086 - loss: 0.3998 - val_accuracy: 0.7610 - val_loss: 0.4790
Epoch 7/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.8099 - loss: 0.3974 - val_accuracy: 0.7594 - val_loss: 0.4794
Epoch 8/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 21s 4ms/step - accuracy: 0.8113 - loss: 0.3960 - val_accuracy: 0.7513 - val_loss: 0.4839
Epoch 9/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 18s 4ms/step - accuracy: 0.8118 - loss: 0.3951 - val_accuracy: 0.7491 - val_loss: 0.4969
Epoch 10/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 24s 5ms/step - accuracy: 0.8131 - loss: 0.3940 - val_accuracy: 0.7455 - val_loss: 0.4856
Epoch 11/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.8142 - loss: 0.3927 - val_accuracy: 0.7569 - val_loss: 0.4790
Epoch 12/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 21s 4ms/step - accuracy: 0.8139 - loss: 0.3922 - val_accuracy: 0.7663 - val_loss: 0.4797
Epoch 13/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 17s 4ms/step - accuracy: 0.8147 - loss: 0.3920 - val_accuracy: 0.7470 - val_loss: 0.4863
Epoch 14/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 20s 4ms/step - accuracy: 0.8153 - loss: 0.3909 - val_accuracy: 0.7531 - val_loss: 0.4839
Epoch 15/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.8157 - loss: 0.3903 - val_accuracy: 0.7637 - val_loss: 0.4773
Epoch 16/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 21s 4ms/step - accuracy: 0.8160 - loss: 0.3899 - val_accuracy: 0.7611 - val_loss: 0.4768
Epoch 17/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.8157 - loss: 0.3897 - val_accuracy: 0.7606 - val_loss: 0.4878
Epoch 18/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 21s 4ms/step - accuracy: 0.8170 - loss: 0.3892 - val_accuracy: 0.7580 - val_loss: 0.4866
Epoch 19/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 21s 4ms/step - accuracy: 0.8170 - loss: 0.3878 - val_accuracy: 0.7569 - val_loss: 0.4861
Epoch 20/20
4975/4975 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - accuracy: 0.8164 - loss: 0.3883 - val_accuracy: 0.7415 - val_loss: 0.4966

In [38]:
loss, accuracy = model_2.evaluate(X_test, y_test)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

1098/1098 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7528 - loss: 0.5287
Test Loss: 0.5286715030670166
Test Accuracy: 0.7527552247047424

In [39]:
loss, accuracy = model_3.evaluate(X_test, y_test)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

1098/1098 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7564 - loss: 0.4937
Test Loss: 0.4937030076980591
Test Accuracy: 0.7563719153404236

In [40]:
loss, accuracy = model_4.evaluate(X_test, y_test)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

1098/1098 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.7090 - loss: 0.5076
Test Loss: 0.5075598359107971
Test Accuracy: 0.7090132236480713

In [41]:
loss, accuracy = model_5.evaluate(X_test, y_test)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

1098/1098 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7415 - loss: 0.4966
Test Loss: 0.49662965536117554
Test Accuracy: 0.7414780259132385

In [28]:
print(pd.Series(y_train).value_counts())
print(pd.Series(y_test).value_counts())

1.0    109290
0.0     49898
Name: count, dtype: int64
1.0    21221
0.0    13894
Name: count, dtype: int64

In [29]:
store = 0
sku = 4
prediction_day = pd.Timestamp("2024-06-11")

In [30]:
group = combined_df[
    (combined_df["store_id"] == store) &
    (combined_df["product_id"] == sku)
].sort_values("dt")

history = group[group["dt"] < prediction_day].tail(LOOKBACK)

if len(history) != LOOKBACK:
    print(len(history))

In [31]:
X = history[feature_cols].values.astype(np.float32)
X = X.reshape(1, LOOKBACK, len(feature_cols))

In [32]:
prob = model.predict(X, verbose=0)[0, 0]

prediction = int(prob >= 0.5)

print("Probability of stockout:", prob)
print("Prediction:", prediction)

Probability of stockout: 0.25843346
Prediction: 0

In [1]:
import shap                                                                                                                                             
import numpy as np                                                                                                                                      
                                                                                                                                                            
    # SHAP needs a "background" dataset to calculate baseline expectations.                                                                                 
    # We'll use a random sample of 100 items from your training data to save time.                                                                          
background = X_train[np.random.choice(X_train.shape[0], 100, replace=False)]                                                                            
                                                                                                                                                            
    # Initialize the DeepExplainer                                                                                                                          
explainer = shap.DeepExplainer(model_2, background)                                                                                                     
                                                                                                                                                            
    # Pick a few test samples you want to explain (e.g., the first 5)                                                                                       
test_samples = X_test[:5]                                                                                                                               
                                                                                                                                                            
    # Calculate SHAP values for these test samples                                                                                                          
shap_values = explainer.shap_values(test_samples)                                                                                                       
                                                                                                                                                            
    # Visualizing the importance of features for the very first prediction                                                                                  
    # We reshape it into 2D to easily view what features at what timesteps mattered most                                                                    
shap.image_plot(shap_values[0].reshape(1, LOOKBACK, X_train.shape[2], 1), -test_samples[0].reshape(1, LOOKBACK, X_train.shape[2], 1))

/home/samyak/code/Labs/BTP_2/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

NameError: name 'X_train' is not defined